### ISSUE TITLE
Script2Pkg doesn't recognise Xcode 16 command line tools for notarization

### ISSUE THREAD

**Issue by dechkovanen** [SAP/script-to-package-tool-for-macos#5] opened 2024-09-27 06:38 UTC
Script2Pkg doesn't detect that command line tools for Xcode 16 (macOS 15 Sequoia) are installed. The Notarize checkbox is greyed out and in settings there is a button to install the tools, despite them being installed and up-to-date.

**Comment by mthielemann** [comment] 2024-09-27 07:36
Just tested this but cannot reproduce it on my end. Could you please make sure you have at least one developer identity in your Keychain? Otherwise Script2Pkg does not really check for the command-line tools. This is a known issue and will be fixed in the next release.

**Comment by dechkovanen** [comment] 2024-09-27 08:38
Thanks. Turns out my developer ID cert was indeed expired, refreshing the cert in Xcode resolved this so that's all good now.

Script2Pkg still happily signed the package using the expired developer identity, though, so it did not occur to me at first that the certificate may be the issue. Therefore some improvement could possibly be made into validating the selected certificate.

**Comment by mthielemann** [comment] 2024-09-27 10:13
This will be fixed in version 1.1.3, which will be available shortly. Thanks for reporting this.

**Closed by mthielemann** 2024-09-27 10:13 UTC

**Comment by mthielemann** [comment] 2024-09-30 09:00
Version 1.1.3 is now available.
